var teamData = [
    {
        name: "Australia",
        img: "https://www.cricket.com/_next/image?url=https%3A%2F%2Fimages.cricket.com%2Fteams%2F1_actionshot_safari.jpg&w=1920&q=75",
        icc: "ICC Ranking",
        test_no: 1,
        odi_no: 5,
        T20_no: 6,
        test: "Test",
        odi: "ODI",
        T20: "T20",
        id: 4
    },
    {
        name: "Afghansitan",
        img: "https://www.cricket.com/_next/image?url=https%3A%2F%2Fimages.cricket.com%2Fteams%2F1188_actionshot_safari.jpg&w=1920&q=75",
        icc: "ICC Ranking",
        test_no: "-",
        odi_no: 10,
        T20_no: 9,
        test: "Test",
        odi: "ODI",
        T20: "T20",
        id: 96
    },
    {
        name: "Bangladesh",
        img: "https://www.cricket.com/_next/image?url=https%3A%2F%2Fimages.cricket.com%2Fteams%2F2_actionshot_safari.jpg&w=1920&q=75",
        icc: "ICC Ranking",
        test_no: 9,
        odi_no: 7,
        T20_no: 10,
        test: "Test",
        odi: "ODI",
        T20: "T20",
        id: 6
    },
    {
        name: "England",
        img: "https://www.cricket.com/_next/image?url=https%3A%2F%2Fimages.cricket.com%2Fteams%2F3_actionshot_safari.jpg&w=1920&q=75",
        icc: "ICC Ranking",
        test_no: 4,
        odi_no: 2,
        T20_no: 2,
        test: "Test",
        odi: "ODI",
        T20: "T20",
        id: 9
    },
    {
        name: "India",
        img: "https://www.cricket.com/_next/image?url=https%3A%2F%2Fimages.cricket.com%2Fteams%2F4_actionshot_safari.jpg&w=1920&q=75",
        icc: "ICC Ranking",
        test_no: 2,
        odi_no: 3,
        T20_no: 1,
        test: "Test",
        odi: "ODI",
        T20: "T20",
        id: 2
    },
    {
        name: "New Zealand",
        img: "https://www.cricket.com/_next/image?url=https%3A%2F%2Fimages.cricket.com%2Fteams%2F5_actionshot_safari.jpg&w=1920&q=75",
        icc: "ICC Ranking",
        test_no: 5,
        odi_no: 1,
        T20_no: 5,
        test: "Test",
        odi: "ODI",
        T20: "T20",
        id: 13
    },
    {
        name: "Pakistan",
        img: "https://www.cricket.com/_next/image?url=https%3A%2F%2Fimages.cricket.com%2Fteams%2F6_actionshot_safari.jpg&w=1920&q=75",
        icc: "ICC Ranking",
        test_no: 6,
        odi_no: 4,
        T20_no: 3,
        test: "Test",
        odi: "ODI",
        T20: "T20",
        id: 3
    },
    {
        name: "South Africa",
        img: "https://www.cricket.com/_next/image?url=https%3A%2F%2Fimages.cricket.com%2Fteams%2F7_actionshot_safari.jpg&w=1920&q=75",
        icc: "ICC Ranking",
        test_no: 3,
        odi_no: 6,
        T20_no: 4,
        test: "Test",
        odi: "ODI",
        T20: "T20",
        id: 11
    },
    {
        name: "Sri Lanka",
        img: "https://www.cricket.com/_next/image?url=https%3A%2F%2Fimages.cricket.com%2Fteams%2F8_actionshot_safari.jpg&w=1920&q=75",
        icc: "ICC Ranking",
        test_no: 7,
        odi_no: 8,
        T20_no: 8,
        test: "Test",
        odi: "ODI",
        T20: "T20",
        id: 5
    },
    {
        name: "West Indies",
        img: "https://www.cricket.com/_next/image?url=https%3A%2F%2Fimages.cricket.com%2Fteams%2F9_actionshot_safari.jpg&w=1920&q=75",
        icc: "ICC Ranking",
        test_no: 8,
        odi_no: 9,
        T20_no: 7,
        test: "Test",
        odi: "ODI",
        T20: "T20",
        id: 10
    }
]